# Tensor Basics

In [1]:
import torch
import numpy as np

## Converting NumPy arrays to PyTorch tensors
 A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.<br>
Calculations between tensors can only happen if the tensors share the same dtype.<br>
 In some cases tensors are used as a replacement for NumPy to use the power of GPUs.

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [3]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [4]:
# Print the type of data held by the tensor
print(x.dtype)

torch.int32


In [5]:
# Print the tensor object type
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.IntTensor


In [6]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [7]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


## Copying vs. sharing

In [8]:
# Using torch.from_numpy()
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [9]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4], dtype=torch.int32)


In [10]:
# Using torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [11]:
arr[2]=77
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


## Class constructors

In [12]:
data = np.array([1,2,3])

In [13]:
a = torch.Tensor(data)  # Equivalent to cc = torch.FloatTensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [14]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3], dtype=torch.int32) torch.IntTensor


In [15]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


## Creating tensors from scratch
### Uninitialized tensors with <tt>.empty()</tt>

In [16]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Initialized tensors with <tt>.zeros()</tt> and <tt>.ones()</tt>

In [17]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Tensors from ranges


In [18]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [19]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


### Tensors from data
<tt>torch.tensor()</tt> will choose the dtype based on incoming data:

In [20]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


In [21]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


In [22]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


### Changing the dtype of existing tensors
Don't be tempted to use <tt>x = torch.tensor(x, dtype=torch.type)</tt> as it will raise an error about improper use of tensor cloning.<br>
Instead, use the tensor <tt>.type()</tt> method.

In [23]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


### Random number tensors

In [24]:
x = torch.rand(4, 3)
print(x)

tensor([[0.7305, 0.9385, 0.4469],
        [0.9338, 0.5603, 0.1390],
        [0.7821, 0.0739, 0.6342],
        [0.3838, 0.7609, 0.9867]])


In [25]:
x = torch.randn(4, 3)
print(x)

tensor([[-0.9620,  1.4057,  0.4696],
        [ 0.4605,  0.8857, -1.1485],
        [-0.6488,  0.6288, -0.8533],
        [-1.1782,  0.5251, -1.5454]])


In [26]:
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[3, 4, 1],
        [1, 1, 0],
        [0, 3, 3],
        [0, 3, 4]])


### Random number tensors that follow the input size

In [27]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [28]:
x2 = torch.randn_like(x)
print(x2)

tensor([[ 0.7569, -0.1724,  1.6844, -0.1149,  0.2305],
        [-0.8895,  0.5379, -0.9446, -1.8419, -0.7422]])


The same syntax can be used with<br>

In [29]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### Setting the random seed

In [30]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [31]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


## Tensor attributes

In [32]:
x.shape

torch.Size([2, 3])

In [33]:
x.size()  # equivalent to x.shape

torch.Size([2, 3])

In [34]:
x.device

device(type='cpu')

In [35]:
x.layout

torch.strided