## Imports

In [2]:
import torch
import numpy as np

## Indexing and Slicing

In [3]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [4]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [5]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])

## Reshaping Tenrsors with .view()

In [6]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
x.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [9]:
# x is unchanged
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Views display the most recent version of the tensor
z = x.view(2,5)
x[0]=234
print(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


In [11]:
# Views can infer the size of one dimension
# By passing -1 pytorch will infer the size of that dimension
x.view(2,-1)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [12]:
x.view(-1,5)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [13]:
# Pass a tensor's shape with .view_as()
x.view_as(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

## Tensor Arithmetic
### Addition can be perfomeed in multiple ways

In [14]:
# using + operator
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


In [15]:
# using torch.add()
print(torch.add(a, b))

tensor([5., 7., 9.])


In [16]:
# using torch.add() with an output tensor
result = torch.empty(3)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([5., 7., 9.])


In [17]:
# in-place addition
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)

tensor([5., 7., 9.])


In [18]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(torch.add(a,b).sum())

tensor(21.)


## Dot Product
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$

$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>

In [20]:
# dot product can be performed using the dot function or by using the dot method
# dot function syntax: torch.dot(tensor1, tensor2)
# dot method syntax: tensor1.dot(tensor2)

a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b)) # for reference
print()
print(a.dot(b))

tensor([ 4., 10., 18.])

tensor(32.)


## Matrix Multiplication

In [21]:
# matrix multiplication can be performed using the mm function or by using the matmul method
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [22]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [23]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [24]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


In [27]:
# broadcasting is the process of making tensors of different shapes behave like each other
# mm can not be used for broadcasting
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


In [28]:
# This will raise a RuntimeError
print(torch.mm(t1, t2).size())

RuntimeError: self must be a matrix

## Advanced Operations

## L2 or Euclidian Norm
torch.norm()

The Euclidian Norm gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
It is calculated as<br>

${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$
