## Imports

In [1]:
import torch
import numpy as np

## Indexing and Slicing

In [2]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [3]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [4]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])